### ISSUE TITLE
针对于最新上传的Icalingua 2.4.5包

### ISSUE THREAD

**Issue by xm-kk** [AtomAlpaca/Icalingua-clone#5]
针对于由 [bcegkmqs23](https://github.com/bcegkmqs23) 构建的 Icalingua 2.4.5，今天做了一个测试发现bcegkmqs23  构建的deb功能包并不能使用，显示无法连接数据库，不知道该版本有没有经过测试呢？

**Comment by elysia-best** [comment]
可以自行构建。
经过测试，官方版本的源码在amd64与arm64环境下打包均通过且可以正常使用。
